name: metaweather
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0"
  flutter: "2.8.1"

dependencies:
  dio: 4.0.4
  flutter:
    sdk: flutter
  flutter_svg: 1.0.3
  json_annotation: 4.4.0
  provider: 6.0.2
  retrofit: 3.0.1+1
  shared_preferences: 2.0.13

dev_dependencies:
  build_runner: 2.1.8
  flutter_lints: 1.0.4
  json_serializable: 6.1.5
  logger: 1.1.0
  retrofit_generator: 4.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
